# Generated by Django 5.0.7 on 2024-08-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_is_agent_profile_is_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_agent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_player',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('agent', 'Agente'), ('player', 'Jugador')], default='player', max_length=10),
        ),
    ]
