# Generated by Django 5.0.7 on 2024-08-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_profile_age_profile_bio_profile_current_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
