# Generated by Django 5.0.7 on 2024-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('base', 'Base'), ('escolta', 'Escola'), ('alero', 'Alero'), ('alapivot', 'Ala-Pivot'), ('pivot', 'Pivot')], max_length=20, null=True),
        ),
    ]
