# Generated by Django 5.0.7 on 2024-08-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_remove_profile_role_alter_profile_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_teams',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
    ]
