# Generated by Django 5.0.7 on 2024-08-29 23:19

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_remove_profile_current_team_remove_profile_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to),
        ),
    ]
