# Generated by Django 5.0.7 on 2024-08-24 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0013_remove_profile_current_team_remove_profile_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('position', models.CharField(choices=[('base', 'Base'), ('escolta', 'Escolta'), ('alero', 'Alero'), ('alapivot', 'Ala-Pivot'), ('pivot', 'Pivot')], max_length=20)),
                ('last_teams', models.TextField(blank=True, null=True)),
                ('current_team', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('not available', 'No Disponible')], max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='registration.profile')),
            ],
        ),
    ]
