# Generated by Django 5.0.7 on 2024-08-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_teams',
        ),
        migrations.AddField(
            model_name='player',
            name='last_teams',
            field=models.ManyToManyField(blank=True, related_name='players', to='players.team'),
        ),
    ]
