# Generated by Django 5.0.7 on 2024-08-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_team_remove_player_current_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_teams',
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
