# Generated by Django 5.0.7 on 2024-08-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_player_last_teams_player_teams_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
