# Generated by Django 5.0.7 on 2024-08-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birthday',
            field=models.DateField(default=None),
        ),
    ]
