# Generated by Django 5.0.7 on 2024-08-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_remove_player_teams_team_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
