# Generated by Django 5.0.7 on 2024-08-26 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_remove_team_player_player_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_teams', to='players.player'),
        ),
    ]
