# Generated by Django 5.0.7 on 2024-08-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
    ]
