# Generated by Django 5.0.7 on 2024-08-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_remove_team_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(related_name='players', to='players.team'),
        ),
    ]
