# Generated by Django 5.0.7 on 2024-08-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_player_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='players.player'),
        ),
    ]
