# Generated by Django 5.0.7 on 2024-08-27 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_alter_team_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='players.player'),
        ),
    ]
