# Generated by Django 5.0.7 on 2024-08-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_alter_team_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
    ]
