# Generated by Django 5.0.7 on 2024-08-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_remove_team_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='players'),
        ),
    ]
