# Generated by Django 5.0.7 on 2024-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_alter_player_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(),
        ),
    ]
