# Generated by Django 5.0.7 on 2024-08-29 23:19

import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_alter_player_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=players.models.custom_upload_to),
        ),
    ]
