# Generated by Django 5.0.7 on 2024-09-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_alter_player_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(default=0.0),
        ),
    ]
