# Generated by Django 5.0.7 on 2024-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_alter_player_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='yt_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
