# Generated by Django 5.0.7 on 2024-09-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_remove_team_year_played_playerteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='year_played',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='PlayerTeam',
        ),
    ]
